language: node_js
node_js:
  - "node"
before_install:
  - "npm install -g https://$GITHUB_ACCESS_TOKEN@github.com/bobby-brennan/lucy-v3"

script:
  - "lucybot build --prerender --basePath /kaltura-recipes-v3/"
  - ./scripts/deploy-to-gh-pages.sh
