openapi: ./openapi.json
basePath: '/workflows/'
embedParameters:
  format: 1
hljsTheme: 'atom-one-light'
jsIncludes:
  - 'assets/kaltura.js'
codegenURL: '/code/build/request'
routes:
  default:
    title: Kaltura VPaaS API
  recipes:
    path: '/workflows'
    title: Kaltura API Workflows
    meta:
      description: "Learn how to work with the Kaltura API using interactive workflows"
  console:
    path: '/console'
    title: Kaltura API Console
  documentation:
    path: '/api-docs'
    title: Kaltura API Documentation
workflowCategories:
  - title: Generate API Sessions
    icon: assets/img/icons/administrative.png
    workflows:
      - authentication
      - app_tokens
  - title: Ingest and Upload Media
    icon: assets/img/icons/upload.png
    workflows:
      - upload
  - title: Live Stream and Broadcast
    icon: assets/img/icons/play-back.png
    workflows:
      - live_broadcast
  - title: Enrich and Organize Metadata
    icon: assets/img/icons/distribute.png
    workflows:
      - metadata
      - captions
      - webvtt_captions
  - title: Search, Discover and Personalize
    icon: assets/img/icons/publish.png
    workflows:
      - video_search
  - title: Engage and Publish
    icon: assets/img/icons/engage.png
    workflows:
      - dynamic_thumbnails
      - player_uiconf
      - player_external_skin_overrides
      - using_css_states
      - code_cue_points
      - quiz
      - ad_cue_points
  - title: Integration, Scheduling and Hooks
    icon: assets/img/icons/analytic.png
    workflows:
      - backend_notifications
      - analytics
  - title: Manage and Deliver Apps and Widgets
    icon: assets/img/icons/manage.png
    workflows:
      - app_tokens
  - title: Other
    icon: assets/img/icons/other.png
    isMiscellaneous: true
  - title: Contact Us
    icon: assets/img/icons/contact.png
    isContact: true
