openapi: ./openapi.json
embedParameters:
  format: 1
hljsTheme: 'atom-one-light'
jsIncludes:
  - 'assets/kaltura.js'
codegen:
  url: '/code/build/request'
  languages:
    - php
    - java
    - node
    - id: csharp
      label: 'C#'
    - ruby
    - javascript
    - html

routes:
  default:
    title: Kaltura VPaaS API
  recipes:
    path: '/workflows'
    title: Kaltura API Workflows
    meta:
      description: "Learn how to work with the Kaltura API using interactive workflows"
  console:
    path: '/console'
    title: Kaltura API Console
  documentation:
    path: '/api-docs'
    title: Kaltura API Documentation
navigation:
  - title: "Overview"
    contents: ./markdown/overview.md
  - title: "Client Libraries"
    contents: ./markdown/generated/client_libraries.md
  - title: "XML Schemas"
    contents: ./markdown/schemas.md
    children:
      - title: 'Syndication Feed'
        contents: ./markdown/generated/syndication.md
        prerender: false
      - title: 'Bulk Upload'
        contents: ./markdown/generated/bulkUploadXml.bulkUploadXML.md
        prerender: false
      - title: 'Bulk Upload Results'
        contents: ./markdown/generated/bulkUploadXml.bulkUploadResultXML.md
        prerender: false
      - title: 'Cue Point Serve'
        contents: ./markdown/generated/cuePoint.serveAPI.md
        prerender: false
      - title: 'Cue Point Ingest'
        contents: ./markdown/generated/cuePoint.ingestAPI.md
        prerender: false
      - title: 'Drop Folder'
        contents: ./markdown/generated/dropFolderXmlBulkUpload.dropFolderXml.md
        prerender: false
  - title: "Generate API Sessions"
    children:
      - title: "session"
        children:
          - operation: "session.start"
          - operation: "session.end"
          - operation: "session.get"
          - operation: "session.impersonate"
          - operation: "session.impersonateByKs"
          - operation: "session.startWidgetSession"
      - tag: "appToken"
      - operation: 'user.loginByLoginId'
  - title: "Ingest and Upload Media"
    children:
      - tag: "uploadToken"
      - tag: "media"
      - tag: "captionAsset"
      - tag: "captionParams"
      - tag: "thumbAsset"
      - tag: "attachmentAsset"
      - tag: "externalMedia"
      - tag: "upload"
        hidden: true
  - title: "Execute Bulk Ingest and Updates"
    children:
      - operation: "media.bulkUploadAdd"
      - operation: "user.addFromBulkUpload"
      - operation: "category.addFromBulkUpload"
      - operation: "cuePoint.addFromBulk"
      - operation: "categoryEntry.addFromBulkUpload"
      - operation: "categoryUser.addFromBulkUpload"
      - tag: "bulk"
      - tag: "schema"
      - tag: "dropFolder"
      - tag: "dropFolderFile"
      - tag: "virusScanProfile"
        hidden: true
      - tag: "aspera"
        hidden: true
      - tag: "bulkUpload"
        hidden: true
  - title: "Convert and Transcode Media"
    children:
      - tag: "flavorAsset"
      - tag: "flavorParams"
      - tag: "flavorParamsOutput"
      - tag: "conversionProfile"
      - tag: "conversionProfileAssetParams"
      - tag: "mediaInfo"
  - title: "Live Stream and Broadcast"
    children:
      - tag: "liveStream"
  - title: "Enrich and Organize Metadata"
    children:
      - tag: "baseEntry"
      - tag: "category"
      - tag: "categoryEntry"
      - tag: "categoryUser"
      - tag: "metadata"
      - tag: "metadataProfile"
      - tag: "captionAsset"
      - tag: "captionParams"
      - tag: "captionAssetItem"
      - tag: "attachmentAsset"
      - tag: "thumbAsset"
      - tag: "thumbParams"
      - tag: "tag"
  - title: "Search, Discover and Personalize"
    children:
      - operation: "baseEntry.list"
      - tag: "captionAssetItem"
      - tag: "playlist"
      - tag: "like"
      - tag: "shortLink"
      - tag: "tag"
      - tag: "user"
      - tag: "groupUser"
  - title: "Engage and Publish"
    children:
      - tag: "playlist"
      - tag: "thumbnail"
      - tag: "cuePoint"
      - tag: "quiz"
      - tag: "userEntry"
      - tag: "like"
      - tag: "uiConf"
      - tag: "annotation"
        hidden: true
  - title: "Review Media Analytics"
    children:
      - tag: "analytics"
      - tag: "report"
      - tag: "liveReports"
      - tag: "liveStats"
      - tag: "stats"
  - title: "Deliver and Distribute Media"
    children:
      - tag: "playManifest"
      - tag: "syndicationFeed"
      - tag: "entryDistribution"
      - tag: "distributionProfile"
      - tag: "distributionProvider"
      - tag: "deliveryProfile"
        hidden: true
      - tag: "storageProfile"
        hidden: true
  - title: "Secure, Control and Govern"
    children:
      - tag: "partner"
      - tag: "user"
      - tag: "userRole"
      - tag: "groupUser"
      - tag: "accessControlProfile"
      - tag: "categoryEntry"
      - tag: "categoryUser"
      - tag: "permission"
      - tag: "permissionItem"
      - tag: "accessControl"
        hidden: true
      - tag: "adminUser"
        hidden: true
      - tag: "auditTrail"
        hidden: true
  - title: "Optimize API Requests"
    children:
      - tag: "multirequest"
      - tag: "responseProfile"
  - title: "Integration, Scheduling and Hooks"
    children:
      - tag: "eventNotificationTemplate"
      - tag: "scheduledTaskProfile"
      - title: "Scheduling Triggers using iCal"
        contents: ./markdown/scheduling.md
        children:
          - tag: "scheduleEvent"
          - tag: "scheduleEventResource"
          - tag: "scheduleResource"
      - tag: "integration"
      - tag: "businessProcessCase"
      - tag: "notification"
        hidden: true
  - title: "Encrypt and License Content"
    children:
      - tag: "drmLicenseAccess"
      - tag: "drmPolicy"
      - tag: "drmProfile"
      - tag: "playReadyDrm"
      - tag: "widevineDrm"
      - tag: "deliveryProfile"
        hidden: true
  - title: "Manage Documents and Other Assets"
    children:
      - tag: "baseEntry"
      - tag: "data"
      - tag: "documents"
  - title: "Manage and Deliver Apps and Widgets"
    children:
      - tag: "uiConf"
      - tag: "widget"
      - tag: "fileAsset"
      - tag: "captureSpace"
  - title: "Manage Backend and Storage"
    children:
      - tag: "system"
      - tag: "storageProfile"
        hidden: true
  - title: "General Objects"
  - title: "Error Codes"
    contents: ./markdown/errors.md


workflowCategories:
  - title: Generate API Sessions
    icon: assets/img/icons/administrative.png
    workflows:
      - authentication
      - app_tokens
  - title: Ingest and Upload Media
    icon: assets/img/icons/upload.png
    workflows:
      - upload
  - title: Live Stream and Broadcast
    icon: assets/img/icons/play-back.png
    workflows:
      - live_broadcast
  - title: Enrich and Organize Metadata
    icon: assets/img/icons/distribute.png
    workflows:
      - metadata
      - captions
      - webvtt_captions
  - title: Search, Discover and Personalize
    icon: assets/img/icons/publish.png
    workflows:
      - video_search
  - title: Engage and Publish
    icon: assets/img/icons/engage.png
    workflows:
      - dynamic_thumbnails
      - player_uiconf
      - player_external_skin_overrides
      - using_css_states
      - code_cue_points
      - quiz
      - ad_cue_points
  - title: Integration, Scheduling and Hooks
    icon: assets/img/icons/analytic.png
    workflows:
      - backend_notifications
      - analytics
  - title: Manage and Deliver Apps and Widgets
    icon: assets/img/icons/manage.png
    workflows:
      - app_tokens
  - title: Other
    icon: assets/img/icons/other.png
    isMiscellaneous: true
  - title: Contact Us
    icon: assets/img/icons/contact.png
    isContact: true
